# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring_services',
            name='host_id',
            field=models.CharField(blank=True, default='null', max_length=30),
        ),
    ]
