global:
  scrape_interval: 15s
  scrape_timeout: 5s
  evaluation_interval: 15s

rule_files:
  - /opt/Monitoring/prometheus/rules/rules.yml

scrape_configs:
  - job_name: 'sonata'
    static_configs:
      - targets: ['pushgateway:9091']
        labels:
          group: development